package com.moonbright.infrastructure.error;

import lombok.Getter;

@Getter
public enum ErrorCodeAndDescription {
    CLIENT_USER_EXISTS_ERROR_CODE("CLIENT_USER_EXISTS_ERROR_CODE"),
    FILE_FORM_OPERATION_ERROR_CODE("FILE_FORM_OPERATION_ERROR_CODE"),
    CLIENT_TOKEN_VERIFICATION_FAILED_ERROR_CODE("CLIENT_TOKEN_VERIFICATION_FAILED_ERROR_CODE"),
    CLIENT_TOKEN_STRUCTURE_IS_NOT_VALID("CLIENT_TOKEN_STRUCTURE_IS_NOT_VALID"),
    CLIENT_APPOINTMENT_ALREADY_EXISTS_ERROR_CODE("CLIENT_APPOINTMENT_ALREADY_EXISTS_ERROR_CODE"),
    USER_ID_NOT_FOUND_ERROR_CODE("USER_ID_NOT_FOUND_ERROR_CODE"),
    ALREADY_EXISTING_FILE_DOC_ERROR_CODE("ALREADY_EXISTING_FILE_DOC_ERROR_CODE");
    private final String errorCode;

    ErrorCodeAndDescription(String errorCode) {
        this.errorCode = errorCode;
    }


}
